{
    'name': 'Home Care',
    'version': '19.0.5.2.2',
    'category': 'Services',
    'summary': 'Home care system — packages, entitlements, workflows, and service requests',
    'description': """
        Manage home care packages, service entitlements, configurable workflows,
        and service request submission from the customer portal.
    """,
    'author': 'm.hekmati',
    'images': ['static/description/icon.png'],
    'depends': [
        'account',
        'product',
        'sale',
        'sale_management',
        'sale_subscription',
        'website',
        'website_sale',
        'portal',
        'mail',
        'sms',
        'oe_sms',
    ],
    'data': [
        'security/home_care_security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/request_category_data.xml',
        'data/care_team_sync.xml',
        'views/care_request_category_views.xml',
        'views/care_team_views.xml',
        'views/care_workflow_views.xml',
        'views/care_insurance_views.xml',
        'views/product_template_views.xml',
        'views/care_entitlement_views.xml',
        'views/care_service_request_views.xml',
        'views/account_move_views.xml',
        'wizard/care_invoice_wizard_views.xml',
        'wizard/care_change_assignee_wizard_views.xml',
        'wizard/care_accept_assignment_wizard_views.xml',
        'views/menu.xml',
        'views/care_dashboard_views.xml',
        'views/portal_templates.xml',
        'views/portal_invoice_done_template.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'home_care/static/src/scss/home_care_portal.scss',
            'home_care/static/src/js/care_portal.js',
            'home_care/static/src/js/care_portal_invoice.js',
            'home_care/static/src/js/care_portal_wizard_modal.js',
            'home_care/static/src/js/portal_home_counters.js',
        ],
    },
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
